### ISSUE TITLE
Please support ARM-based machine

### ISSUE THREAD

**Issue by nth347** [gezp/docker-ubuntu-desktop#18]
I got the following error while running `docker run -d --restart=on-failure --name my_workspace --cap-add=SYS_PTRACE --gpus all --shm-size=1024m -p 10022:22 -p 14000:4000  gezp/ubuntu-desktop:22.04-cu12.1.1`:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
9254d6b71b2a006637d0597e84d90a3781dcb2e4a3a538aee3ef783060233443
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

**Comment by gezp** [comment]
I have tried to support it, but failed due to no release of Chrome browser for arm64, i don't know how to solve this problem, so i have no plan to support arm64 platform.

**Comment by gezp** [comment]
i use firefox instead of chrome browser, now, ubuntu desktop image for arm64 is supported! I only test image tag `22.04` on Raspberry Pi 4B with ubuntu desktop OS, it works well, but hardware GPU accelerated rendering isn't verified due to no nvidia gpu  on this platform. 

by the way, which arm device do you use? the performance of arm device is poor and there are limited resources at chip, such as small memory space, and the desktop image is heavy compared to other normal docker image，so i don't think it's a good idea to run this image on arm devices.

**Comment by gezp** [comment]
done!
