### ISSUE TITLE
Can I change the xfce4 desktop to others?

### ISSUE THREAD

**Issue by Mr-Python-in-China** [gezp/docker-ubuntu-desktop#21]

**Comment by gezp** [comment]
yes, you can select different desktop environment by  editing Dockerfile：
* use apt to install different desktop environment instead of xfce4.
* replace the value of key `DefaultDesktopCommand` in `/usr/NX/etc/node.cfg` for different  desktop setup.

there are some references： https://forum.nomachine.com/topic/selecting-different-desktop-environment-nomachine-5

**Comment by Mr-Python-in-China** [comment]
Thank you
